# -*- coding: utf-8 -*-
"""Dados_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13fMCU3uhVbVSJCjsrnuHJ4sNc8WQUYgO?authuser=0#scrollTo=H7JZNkorSe2i

## Dados com Python

## Aula 1 - Análise de Dados com *Pandas*
"""

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

df.head()

df.info()

df.describe()

df.shape

linhas, colunas = df.shape[0], df.shape[1]
print('Linhas:', linhas)
print('Colunas:', colunas)

df.columns

# Dicionário de renomeação
novos_nomes = {
    'work_year': 'ano',
    'experience_level': 'senioridade',
    'employment_type': 'contrato',
    'job_title': 'cargo',
    'salary': 'salario',
    'salary_currency': 'moeda',
    'salary_in_usd': 'usd',
    'employee_residence': 'residencia',
    'remote_ratio': 'remoto',
    'company_location': 'empresa',
    'company_size': 'tamanho_empresa'
}

# Aplicando renomeação
df.rename(columns=novos_nomes, inplace=True)

# Verificando resultado
df.head()

# O método .value_counts() serve para contar quantas vezes cada valor único aparece em uma coluna.
df['senioridade'].value_counts()

df['contrato'].value_counts()

df['remoto'].value_counts()

df['tamanho_empresa'].value_counts()

senioridade = {
    'SE': 'senior',
    'MI': 'pleno',
    'EN': 'junior',
    'EX': 'executivo'
}
df['senioridade'] = df['senioridade'].replace(senioridade)
df['senioridade'].value_counts()

contrato = {
    'FT': 'integral',
    'PT': 'parcial',
    'CT': 'contrato',
    'FL': 'freelancer'
}
df['contrato'] = df['contrato'].replace(contrato)
df['contrato'].value_counts()

tamanho_empresa = {
    'L': 'grande',
    'S': 'pequena',
    'M':	'media'

}
df['tamanho_empresa'] = df['tamanho_empresa'].replace(tamanho_empresa)
df['tamanho_empresa'].value_counts()

mapa_trabalho = {
    0: 'presencial',
    100: 'remoto',
    50: 'hibrido'
}

df['remoto'] = df['remoto'].replace(mapa_trabalho)
df['remoto'].value_counts()

df.head()

df.describe(include='object')

"""## Aula 2 - Preparação e limpeza dos Dados"""

df.head()

df.isnull().sum()

df['ano'].unique()

df[df.isnull().any(axis=1)]

# Importação da biblioteca Numpy
import numpy as np

# Criação de um DataFrame para testes.
df_salarios = pd.DataFrame({
    'nome': ['Jhonatan', 'Isadora', 'Joao', 'Julia', 'Cristiano'],
    'salario': [4000, np.nan, 5000, np.nan, 1000000 ]
})

# Calcula a média salarial e substitui os nulos pela média e arredonda os valores
df_salarios['salario_media'] = df_salarios['salario'].fillna(df_salarios['salario'].mean().round(2))
df_salarios

# Calcula a mediana e substitui os nulos pela mediana
df_salarios['salario_mediana'] = df_salarios['salario'].fillna(df_salarios['salario'].median())
df_salarios

# Criação de um DataFrame para testes

df_temperaturas = pd.DataFrame({
    "Dia": ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta'],
    "Temperatura": [30, np.nan, np.nan, 28, 27]

})
df_temperaturas['Preenchido_bfill'] = df_temperaturas['Temperatura'].bfill()
df_temperaturas

df_cidades = pd.DataFrame({
    'nome': ['Jhonatan', 'Isadora', 'Joao', 'Julia', 'Cristiano'],
    'cidade':['Sao Paulo', np.nan, 'Curitiba', np.nan, 'Belém']
})

df_cidades['cidade_preenchida'] = df_cidades['cidade'].fillna('não informado')
df_cidades

df_limpo = df.dropna()

df_limpo.isnull().sum()

df_limpo.head()

# Mostro as informações do meu DataFrame

df_limpo.info()

# Substituição do tipo do numero da coluna ano , passou de float64 para int64.

df_limpo = df_limpo.assign(ano = df_limpo['ano'].astype('int64'))
df_limpo



"""# Aula 3 - Crie Gráficos e conte historias com Dados"""

df_limpo.head()

df_limpo['senioridade'].value_counts().plot(kind='bar', title='Distribuição de Senioridade')

import seaborn as sns

sns.barplot(data = df_limpo, x='senioridade', y='usd')

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))
sns.barplot(data = df_limpo, x='senioridade', y='usd')
plt.title('Salário médio por Senioridade')
plt.xlabel('Senioridade')
plt.ylabel('Salário médio anual (USD)')
plt.show()

df_limpo.groupby('senioridade')['usd'].mean().sort_values(ascending=True)

ordem = df_limpo.groupby('senioridade')['usd'].mean().sort_values(ascending=True).index
ordem

plt.figure(figsize=(8, 5))
sns.barplot(data = df_limpo, x='senioridade', y='usd', order=ordem)
plt.title('Salário médio por Senioridade')
plt.xlabel('Senioridade')
plt.ylabel('Salário médio anual (USD)')
plt.show()

plt.figure(figsize=(10, 5))
sns.histplot(df_limpo['usd'], bins = 50, kde=True)
plt.title('Distribuição dos salários anuais')
plt.xlabel('Salário em USD')
plt.ylabel('Frequência')
plt.show()

plt.figure(figsize=(8, 5))
sns.boxplot(x=df_limpo['usd'])
plt.title('Boxplot salário')
plt.xlabel('Salário em USD')
plt.show()

ordem_senioridade = ['junior', 'pleno', 'senior', 'executivo']

plt.figure(figsize=(8, 5))
sns.boxplot(x='senioridade', y='usd', data=df_limpo, order=ordem_senioridade)
plt.title('Boxplot Distribuição por Senioridade')
plt.xlabel('Salário em USD')
plt.show()

ordem_senioridade = ['junior', 'pleno', 'senior', 'executivo']

plt.figure(figsize=(8, 5))
sns.boxplot(x='senioridade', y='usd', data=df_limpo, order=ordem_senioridade, palette='Set2', hue='senioridade')
plt.title('Boxplot Distribuição por Senioridade')
plt.xlabel('Salário em USD')
plt.show()

import plotly.express as px

df_data_scientist = df_limpo[df_limpo['cargo'] == 'Data Scientist']
salario_medio_por_pais = df_data_scientist.groupby('residencia')['usd'].mean().reset_index()

fig = px.bar(
    salario_medio_por_pais,
    x='residencia',
    y='usd',
    title='Salário Médio de Data Scientists por País',
    labels={'residencia': 'País', 'usd': 'Salário Médio Anual (USD)'},
    color='residencia' # Adiciona cores diferentes para cada país
)

fig.update_layout(xaxis_title='País', yaxis_title='Salário Médio Anual (USD)')
fig.show()

remoto_contagem = df_limpo['remoto'].value_counts().reset_index()
remoto_contagem.columns = ['tipo_trabalho', 'quantidade']

fig = px.pie(remoto_contagem,
    names='tipo_trabalho',
    values = 'quantidade',
    title ='Proporção dos tipos de trabalho',
)

fig.show()

remoto_contagem = df_limpo['remoto'].value_counts().reset_index()
remoto_contagem.columns = ['tipo_trabalho', 'quantidade']

fig = px.pie(remoto_contagem,
    names='tipo_trabalho',
    values = 'quantidade',
    title ='Proporção dos tipos de trabalho',
    hole=0.5

)

fig.show()

remoto_contagem = df_limpo['remoto'].value_counts().reset_index()
remoto_contagem.columns = ['tipo_trabalho', 'quantidade']

fig = px.pie(remoto_contagem,
    names='tipo_trabalho',
    values = 'quantidade',
    title ='Proporção dos tipos de trabalho',
    hole=0.5

)

fig.update_traces(textinfo='percent+label')
fig.show()

df_data_scientist = df_limpo[df_limpo['cargo'] == 'Data Scientist']
salario_medio_por_pais = df_data_scientist.groupby('residencia')['usd'].mean().reset_index()

fig = px.bar(
    salario_medio_por_pais,
    x='residencia',
    y='usd',
    title='Salário Médio de Data Scientists por País',
    labels={'residencia': 'País', 'usd': 'Salário Médio Anual (USD)'},
    color='residencia', # Mantém a diferenciação por residência
    template='plotly_dark',
    color_discrete_sequence=px.colors.sequential.Plasma # Usa uma sequência de cores mais escura, como Plasma
)

fig.update_layout(xaxis_title='País', yaxis_title='Salário Médio Anual (USD)')
fig.show()
